#!/usr/bin/awk -f 

# This doesn't guarantee paths are local, but it tries!

BEGIN {
  any_error = "0"
}

/home\// {
  if (any_error == "1"){
    printf " "
  }
  printf "home"
  any_error = "1"
}

/mosttrusted\// {
  if (any_error == "1"){
    printf " "
  }
  printf "mosttrusted "
  any_error = "1"
}

/brad\// {
  if (any_error == "1"){
    printf " "
  }
  printf "brad "
  any_error = "1"
}

/modengine\// { 
  if (any_error == "1"){
    printf " "
  }
  printf "modengine "
  any_error = "1"
}

END {
  if (any_error == "1"){
    exit(1)
  }
}
